import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:material_ui/material_ui.dart';
import 'package:signals/signals_flutter.dart';

const Color kOrange = Color(0xFFFCB075);
const Color kPurple = Color(0xFF815AA3);
const Color kPink = Color(0xFFEBA1A6);

final Signal<FlexScheme> sFlexScheme = Signal<FlexScheme>(
  FlexScheme.shark,
  options: const SignalOptions<FlexScheme>(name: 'sFlexScheme'),
);

final Signal<bool> sDarkMode = Signal<bool>(
  true,
  options: const SignalOptions<bool>(name: 'sDarkMode'),
);

final Signal<bool> sWakelock = Signal<bool>(
  true,
  options: const SignalOptions<bool>(name: 'sWakelock'),
);

final Signal<String> sFont = Signal<String>(
  'Teko',
  options: const SignalOptions<String>(name: 'sFont'),
);

final Signal<bool> sUseLbs = Signal<bool>(
  false,
  options: const SignalOptions<bool>(name: 'sUseLbs'),
);

final Signal<bool> sAutoStartRestTimer = Signal<bool>(
  false,
  options: const SignalOptions<bool>(name: 'sAutoStartRestTimer'),
);

final Signal<String> sLastShownWeeklySummaryKey = Signal<String>(
  '',
  options: const SignalOptions<String>(name: 'sLastShownWeeklySummaryKey'),
);

final Signal<Map<int, String>> sExerciseNotes = Signal<Map<int, String>>(
  const <int, String>{},
  options: const SignalOptions<Map<int, String>>(name: 'sExerciseNotes'),
);

// Override textTheme for the XL fonts.
const TextTheme _textThemeOverrides = TextTheme(
  displayLarge: TextStyle(fontFamily: 'Bebas Neue'),
  displayMedium: TextStyle(fontFamily: 'Bebas Neue'),
  displaySmall: TextStyle(fontFamily: 'Bebas Neue'),
);

final Computed<ThemeData> cThemeData = Computed<ThemeData>(() {
  final FlexScheme activeScheme = sFlexScheme.value;

  if (sDarkMode.value) {
    return FlexThemeData.dark(
      // Using FlexColorScheme built-in FlexScheme enum based colors.
      scheme: activeScheme,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.seeded,
      // Surface color adjustments.
      surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
      blendLevel: 4,
      // Convenience direct styling properties.
      bottomAppBarElevation: 3.0,
      // Component theme configurations for dark mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnLevel: 4,
        blendOnColors: true,
        scaffoldBackgroundBaseColor:
            FlexScaffoldBaseColor.surfaceContainerLowest,
        useMaterial3Typography: true,
        useM2StyleDividerInM3: true,
        splashType: FlexSplashType.inkSparkle,
        defaultRadius: 6.0,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.0,
        textButtonSchemeColor: SchemeColor.secondary,
        filledButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSecondarySchemeColor: SchemeColor.onSecondary,
        outlinedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.secondary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.secondary,
        toggleButtonsBorderSchemeColor: SchemeColor.secondary,
        segmentedButtonSchemeColor: SchemeColor.secondary,
        segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        segmentedButtonUnselectedSchemeColor: SchemeColor.transparent,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.secondary,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        checkboxSchemeColor: SchemeColor.secondary,
        radioSchemeColor: SchemeColor.secondary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.secondary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.secondary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onlyForDiscrete,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.secondary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.tertiaryContainer,
        progressIndicatorCircularTrackSchemeColor:
            SchemeColor.tertiaryContainer,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 6,
        progressIndicatorStopIndicatorRadius: 6,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorStrokeAlign: -0.5,
        progressIndicatorTrackGap: 6.0,
        progressIndicatorStrokeCap: StrokeCap.round,
        progressIndicatorConstraints: BoxConstraints(
          minWidth: 40,
          minHeight: 40,
        ),
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          0.0,
          0.0,
          0.0,
          0.0,
        ),
        inputDecoratorSchemeColor: SchemeColor.surfaceContainerHighest,
        inputDecoratorIsFilled: true,
        inputDecoratorBackgroundAlpha: 255,
        inputDecoratorBorderSchemeColor: SchemeColor.secondary,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.onSurfaceVariant,
        inputDecoratorSuffixIconSchemeColor: SchemeColor.onSurfaceVariant,
        inputCursorSchemeColor: SchemeColor.surfaceContainerHighest,
        inputSelectionSchemeColor: SchemeColor.surfaceContainerHighest,
        inputSelectionOpacity: 0.50,
        inputSelectionHandleSchemeColor: SchemeColor.surfaceContainerHighest,
        listTileSelectedSchemeColor: SchemeColor.secondary,
        listTileIconSchemeColor: SchemeColor.secondary,
        listTileTileSchemeColor: SchemeColor.transparent,
        listTileSelectedTileSchemeColor: SchemeColor.transparent,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileHorizontalTitleGap: 20.0,
        listTileMinVerticalPadding: 8.0,
        listTileStyle: ListTileStyle.list,
        listTileTitleAlignment: ListTileTitleAlignment.threeLine,
        fabUseShape: true,
        fabRadius: 8.0,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.secondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        chipBlendColors: false,
        chipPadding: EdgeInsetsDirectional.fromSTEB(4, 4, 4, 4),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardBorderSchemeColor: SchemeColor.secondary,
        cardElevation: 3.0,
        popupMenuRadius: 6.0,
        popupMenuElevation: 3.0,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        alignedDropdown: true,
        tooltipRadius: 6.000000000000001,
        tooltipWaitDuration: Duration(milliseconds: 100),
        dialogBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        dialogElevation: 3.0,
        useInputDecoratorThemeInDialogs: true,
        timePickerElementRadius: 6.0,
        datePickerHeaderBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        datePickerHeaderForegroundSchemeColor: SchemeColor.onSurfaceVariant,
        datePickerDividerSchemeColor: SchemeColor.secondary,
        snackBarRadius: 6.000000000000001,
        snackBarElevation: 3,
        snackBarBackgroundSchemeColor: SchemeColor.secondary,
        snackBarActionSchemeColor: SchemeColor.onSecondary,
        appBarForegroundSchemeColor: SchemeColor.secondary,
        appBarIconSchemeColor: SchemeColor.onSurface,
        appBarActionsIconSchemeColor: SchemeColor.onSurfaceVariant,
        appBarScrolledUnderElevation: 3.0,
        appBarCenterTitle: true,
        bottomAppBarSchemeColor: SchemeColor.surfaceContainer,
        bottomAppBarHeight: 56,
        tabBarItemSchemeColor: SchemeColor.secondary,
        tabBarUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        tabBarUnselectedItemOpacity: 0.85,
        tabBarIndicatorSchemeColor: SchemeColor.secondary,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 6,
        tabBarIndicatorTopRadius: 6,
        tabBarDividerColor: Color(0x00000000),
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        drawerElevation: 3.0,
        drawerBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        drawerWidth: 256.0,
        drawerIndicatorWidth: 220.0,
        drawerIndicatorSchemeColor: SchemeColor.secondary,
        drawerSelectedItemSchemeColor: SchemeColor.onSecondary,
        drawerUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetElevation: 3.0,
        bottomSheetModalElevation: 3.0,
        bottomSheetClipBehavior: Clip.none,
        bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarSelectedLabelSize: 14,
        bottomNavigationBarUnselectedLabelSize: 12,
        bottomNavigationBarSelectedIconSize: 24,
        bottomNavigationBarUnselectedIconSize: 20,
        menuRadius: 6.0,
        menuElevation: 3.0,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuPadding: EdgeInsetsDirectional.fromSTEB(0, 0, 0, 0),
        menuBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuBarRadius: 6.0,
        menuBarElevation: 3.0,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorRadius: 6.0,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchBarElevation: 3.0,
        searchViewElevation: 3.0,
        searchBarRadius: 6.0,
        searchViewRadius: 6.0,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationBarMutedUnselectedLabel: true,
        navigationBarSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
        navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        navigationBarElevation: 3.0,
        navigationBarHeight: 64.0,
        navigationBarLabelBehavior:
            NavigationDestinationLabelBehavior.onlyShowSelected,
        navigationBarSelectedLabelSize: 14,
        navigationBarUnselectedLabelSize: 12,
        navigationBarSelectedIconSize: 24,
        navigationBarUnselectedIconSize: 20,
        navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurfaceVariant,
        navigationRailMutedUnselectedLabel: true,
        navigationRailSelectedIconSchemeColor: SchemeColor.onSecondary,
        navigationRailUnselectedIconSchemeColor: SchemeColor.onSurfaceVariant,
        navigationRailMutedUnselectedIcon: true,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.secondary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailElevation: 3.0,
        navigationRailLabelType: NavigationRailLabelType.selected,
        navigationRailSelectedLabelSize: 14,
        navigationRailUnselectedLabelSize: 12,
        navigationRailSelectedIconSize: 24,
        navigationRailUnselectedIconSize: 20,
        navigationRailMinWidth: 72,
        navigationRailMinExtendedWidth: 256,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.compact,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: sFont.value,
      textTheme: _textThemeOverrides,
    );
  } else {
    return FlexThemeData.light(
      // Using FlexColorScheme built-in FlexScheme enum based colors
      scheme: activeScheme,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.seeded,
      // Surface color adjustments.
      surfaceMode: FlexSurfaceMode.level,
      blendLevel: 4,
      // Component theme configurations for light mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnLevel: 4,
        useMaterial3Typography: true,
        useM2StyleDividerInM3: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.0,
        splashType: FlexSplashType.inkSparkle,
        defaultRadius: 6.0,
        textButtonSchemeColor: SchemeColor.secondary,
        filledButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSecondarySchemeColor: SchemeColor.onSecondary,
        outlinedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.secondary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.secondary,
        toggleButtonsBorderSchemeColor: SchemeColor.secondary,
        segmentedButtonSchemeColor: SchemeColor.secondary,
        segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        segmentedButtonUnselectedSchemeColor: SchemeColor.transparent,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.secondary,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        checkboxSchemeColor: SchemeColor.secondary,
        radioSchemeColor: SchemeColor.secondary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.secondary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.secondary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onlyForDiscrete,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.secondary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.tertiaryContainer,
        progressIndicatorCircularTrackSchemeColor:
            SchemeColor.tertiaryContainer,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 6,
        progressIndicatorStopIndicatorRadius: 6,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorStrokeAlign: -0.5,
        progressIndicatorTrackGap: 6.0,
        progressIndicatorStrokeCap: StrokeCap.round,
        progressIndicatorConstraints: BoxConstraints(
          minWidth: 40,
          minHeight: 40,
        ),
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          0.0,
          0.0,
          0.0,
          0.0,
        ),
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        listTileSelectedSchemeColor: SchemeColor.secondary,
        listTileIconSchemeColor: SchemeColor.secondary,
        listTileTileSchemeColor: SchemeColor.transparent,
        listTileSelectedTileSchemeColor: SchemeColor.transparent,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileHorizontalTitleGap: 20.0,
        listTileMinVerticalPadding: 8.0,
        listTileStyle: ListTileStyle.list,
        listTileTitleAlignment: ListTileTitleAlignment.threeLine,
        fabUseShape: true,
        fabRadius: 8.0,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.secondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        chipBlendColors: false,
        chipPadding: EdgeInsetsDirectional.fromSTEB(4, 4, 4, 4),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardBorderSchemeColor: SchemeColor.secondary,
        cardElevation: 3.0,
        popupMenuRadius: 6.0,
        popupMenuElevation: 3.0,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        alignedDropdown: true,
        tooltipRadius: 6.000000000000001,
        tooltipWaitDuration: Duration(milliseconds: 100),
        dialogElevation: 3.0,
        useInputDecoratorThemeInDialogs: true,
        timePickerElementRadius: 6.0,
        datePickerHeaderBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        datePickerHeaderForegroundSchemeColor: SchemeColor.onSurfaceVariant,
        datePickerDividerSchemeColor: SchemeColor.secondary,
        snackBarRadius: 6.000000000000001,
        snackBarElevation: 3,
        snackBarBackgroundSchemeColor: SchemeColor.secondary,
        snackBarActionSchemeColor: SchemeColor.onSecondary,
        appBarCenterTitle: true,
        bottomAppBarHeight: 56,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 6,
        tabBarIndicatorTopRadius: 6,
        tabBarDividerColor: Color(0x00000000),
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        drawerElevation: 3.0,
        drawerBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        drawerWidth: 256.0,
        drawerIndicatorWidth: 220.0,
        drawerIndicatorSchemeColor: SchemeColor.secondary,
        drawerSelectedItemSchemeColor: SchemeColor.onSecondary,
        drawerUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetElevation: 3.0,
        bottomSheetModalElevation: 3.0,
        bottomSheetClipBehavior: Clip.none,
        bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarSelectedLabelSize: 14,
        bottomNavigationBarUnselectedLabelSize: 12,
        bottomNavigationBarSelectedIconSize: 24,
        bottomNavigationBarUnselectedIconSize: 20,
        menuRadius: 6.0,
        menuElevation: 3.0,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuPadding: EdgeInsetsDirectional.fromSTEB(0, 0, 0, 0),
        menuBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuBarRadius: 6.0,
        menuBarElevation: 3.0,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorRadius: 6.0,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchBarElevation: 3.0,
        searchViewElevation: 3.0,
        searchBarRadius: 6.0,
        searchViewRadius: 6.0,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationBarMutedUnselectedLabel: true,
        navigationBarSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
        navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        navigationBarElevation: 3.0,
        navigationBarHeight: 64.0,
        navigationBarLabelBehavior:
            NavigationDestinationLabelBehavior.onlyShowSelected,
        navigationBarSelectedLabelSize: 14,
        navigationBarUnselectedLabelSize: 12,
        navigationBarSelectedIconSize: 24,
        navigationBarUnselectedIconSize: 20,
        navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurfaceVariant,
        navigationRailMutedUnselectedLabel: true,
        navigationRailSelectedIconSchemeColor: SchemeColor.onSecondary,
        navigationRailUnselectedIconSchemeColor: SchemeColor.onSurfaceVariant,
        navigationRailMutedUnselectedIcon: true,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.secondary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailElevation: 3.0,
        navigationRailLabelType: NavigationRailLabelType.selected,
        navigationRailSelectedLabelSize: 14,
        navigationRailUnselectedLabelSize: 12,
        navigationRailSelectedIconSize: 24,
        navigationRailUnselectedIconSize: 20,
        navigationRailMinWidth: 72,
        navigationRailMinExtendedWidth: 256,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.compact,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: sFont.value,
      textTheme: _textThemeOverrides,
    );
  }
});
