import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:material_ui/material_ui.dart';
import 'package:signals/signals_flutter.dart';

const Color kOrange = Color(0xFFFCB075);
const Color kPurple = Color(0xFF815AA3);
const Color kPink = Color(0xFFEBA1A6);

final Signal<FlexScheme> sFlexScheme = Signal<FlexScheme>(
  FlexScheme.shark,
  options: const SignalOptions<FlexScheme>(name: 'sFlexScheme'),
);

final Signal<bool> sDarkMode = Signal<bool>(
  true,
  options: const SignalOptions<bool>(name: 'sDarkMode'),
);

final Signal<bool> sWakelock = Signal<bool>(
  true,
  options: const SignalOptions<bool>(name: 'sWakelock'),
);

final Signal<String> sFont = Signal<String>(
  'Teko',
  options: const SignalOptions<String>(name: 'sFont'),
);

final Signal<bool> sUseLbs = Signal<bool>(
  false,
  options: const SignalOptions<bool>(name: 'sUseLbs'),
);

// Override textTheme for the XL fonts.
const TextTheme _textThemeOverrides = TextTheme(
  displayLarge: TextStyle(fontFamily: 'Bebas Neue'),
  displayMedium: TextStyle(fontFamily: 'Bebas Neue'),
  displaySmall: TextStyle(fontFamily: 'Bebas Neue'),
);

final Computed<ThemeData> cThemeData = Computed<ThemeData>(() {
  final FlexScheme activeScheme = sFlexScheme.value;

  if (sDarkMode.value) {
    return FlexThemeData.dark(
      // Using FlexColorScheme built-in FlexScheme enum based colors.
      scheme: activeScheme,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.seeded,
      // Convenience direct styling properties.
      tooltipsMatchBackground: true,
      // Component theme configurations for dark mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnColors: true,
        useMaterial3Typography: true,
        useM2StyleDividerInM3: true,
        splashType: FlexSplashType.inkSparkle,
        defaultRadius: 4,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        filledButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.primary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onPrimary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.outline,
        segmentedButtonSchemeColor: SchemeColor.secondaryContainer,
        segmentedButtonSelectedForegroundSchemeColor:
            SchemeColor.onSecondaryContainer,
        segmentedButtonUnselectedSchemeColor: SchemeColor.transparent,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.outline,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        switchThumbFixedSize: true,
        switchAdaptiveCupertinoLike: FlexAdaptive.all(),
        checkboxSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.primary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.primary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onlyForDiscrete,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.primary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.secondaryContainer,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 8,
        progressIndicatorStopIndicatorRadius: 8,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorTrackGap: 6,
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          2,
          2,
          2,
          2,
        ),
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorIsDense: true,
        inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(
          8,
          16,
          8,
          8,
        ),
        inputDecoratorBackgroundAlpha: 45,
        inputDecoratorBorderSchemeColor: SchemeColor.primary,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorRadius: 8,
        inputDecoratorUnfocusedHasBorder: false,
        inputDecoratorFocusedBorderWidth: 1,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primaryFixed,
        inputCursorSchemeColor: SchemeColor.primary,
        inputSelectionSchemeColor: SchemeColor.primary,
        inputSelectionHandleSchemeColor: SchemeColor.primary,
        listTileSelectedSchemeColor: SchemeColor.primary,
        listTileIconSchemeColor: SchemeColor.onSurfaceVariant,
        listTileTileSchemeColor: SchemeColor.transparent,
        listTileSelectedTileSchemeColor: SchemeColor.transparent,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileMinVerticalPadding: 4,
        fabUseShape: true,
        fabRadius: 8,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.secondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.onSurfaceVariant,
        chipBlendColors: false,
        chipPadding: EdgeInsets.fromLTRB(8, 10, 8, 10),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardBorderSchemeColor: SchemeColor.outlineVariant,
        cardRadius: 4,
        popupMenuRadius: 8,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        popupMenuOpacity: 0.90,
        alignedDropdown: true,
        snackBarRadius: 4,
        appBarForegroundSchemeColor: SchemeColor.onSurface,
        appBarIconSchemeColor: SchemeColor.onSurface,
        appBarActionsIconSchemeColor: SchemeColor.onSurfaceVariant,
        appBarCenterTitle: true,
        bottomAppBarSchemeColor: SchemeColor.surfaceContainer,
        bottomAppBarHeight: 80,
        tabBarItemSchemeColor: SchemeColor.secondary,
        tabBarUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 4,
        tabBarIndicatorTopRadius: 4,
        tabBarDividerColor: Color(0x00000000),
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarSelectedLabelSize: 12,
        bottomNavigationBarUnselectedIconSize: 20,
        menuRadius: 8,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorRadius: 8,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchUseGlobalShape: true,
        navigationRailUseIndicator: true,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.compact,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: sFont.value,
      textTheme: _textThemeOverrides,
    );
  } else {
    return FlexThemeData.light(
      // Using FlexColorScheme built-in FlexScheme enum based colors
      scheme: FlexScheme.shark,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.seeded,
      // Convenience direct styling properties.
      tooltipsMatchBackground: true,
      // Component theme configurations for light mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useMaterial3Typography: true,
        useM2StyleDividerInM3: true,
        splashType: FlexSplashType.inkSparkle,
        defaultRadius: 4,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        filledButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.primary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onPrimary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.outline,
        segmentedButtonSchemeColor: SchemeColor.secondaryContainer,
        segmentedButtonSelectedForegroundSchemeColor:
            SchemeColor.onSecondaryContainer,
        segmentedButtonUnselectedSchemeColor: SchemeColor.transparent,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.outline,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        switchThumbFixedSize: true,
        switchAdaptiveCupertinoLike: FlexAdaptive.all(),
        checkboxSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.primary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.primary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onlyForDiscrete,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.primary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.secondaryContainer,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 8,
        progressIndicatorStopIndicatorRadius: 8,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorTrackGap: 6,
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          2,
          2,
          2,
          2,
        ),
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorIsDense: true,
        inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(
          8,
          16,
          8,
          8,
        ),
        inputDecoratorBackgroundAlpha: 14,
        inputDecoratorBorderSchemeColor: SchemeColor.primary,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorRadius: 8,
        inputDecoratorUnfocusedHasBorder: false,
        inputDecoratorFocusedBorderWidth: 1,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.onPrimaryFixedVariant,
        listTileSelectedSchemeColor: SchemeColor.primary,
        listTileIconSchemeColor: SchemeColor.onSurfaceVariant,
        listTileTileSchemeColor: SchemeColor.transparent,
        listTileSelectedTileSchemeColor: SchemeColor.transparent,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileMinVerticalPadding: 4,
        fabUseShape: true,
        fabRadius: 8,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.secondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.onSurfaceVariant,
        chipBlendColors: false,
        chipPadding: EdgeInsets.fromLTRB(8, 10, 8, 10),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardBorderSchemeColor: SchemeColor.outlineVariant,
        cardRadius: 4,
        popupMenuRadius: 8,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        popupMenuOpacity: 0.90,
        alignedDropdown: true,
        snackBarRadius: 4,
        appBarCenterTitle: true,
        bottomAppBarHeight: 80,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 4,
        tabBarIndicatorTopRadius: 4,
        tabBarDividerColor: Color(0x00000000),
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarSelectedLabelSize: 12,
        bottomNavigationBarUnselectedIconSize: 20,
        menuRadius: 8,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorForegroundSchemeColor: SchemeColor.onSurface,
        menuIndicatorRadius: 8,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchUseGlobalShape: true,
        navigationRailUseIndicator: true,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.compact,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: sFont.value,
      textTheme: _textThemeOverrides,
    );
  }
});
