// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxd6cu50FNP0l-5Ys_uYTri7CfmaiRb3M',
    appId: '1:319450241016:web:6fdc418e1b99c9fe89e80d',
    messagingSenderId: '319450241016',
    projectId: 'gymplyapp',
    authDomain: 'gymplyapp.firebaseapp.com',
    storageBucket: 'gymplyapp.firebasestorage.app',
    measurementId: 'G-3WDPX7LEXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVHHv6lJhP7szzm-R2x1mTlwCUDFf2de4',
    appId: '1:319450241016:android:a3f02c0f36a138b589e80d',
    messagingSenderId: '319450241016',
    projectId: 'gymplyapp',
    storageBucket: 'gymplyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETwGqkWGsnMAqPPpTULFBLxmE58HmKMs',
    appId: '1:319450241016:ios:607d0ef917d749bd89e80d',
    messagingSenderId: '319450241016',
    projectId: 'gymplyapp',
    storageBucket: 'gymplyapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.gymply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETwGqkWGsnMAqPPpTULFBLxmE58HmKMs',
    appId: '1:319450241016:ios:607d0ef917d749bd89e80d',
    messagingSenderId: '319450241016',
    projectId: 'gymplyapp',
    storageBucket: 'gymplyapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.gymply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxd6cu50FNP0l-5Ys_uYTri7CfmaiRb3M',
    appId: '1:319450241016:web:8d2481d33b0bcd4b89e80d',
    messagingSenderId: '319450241016',
    projectId: 'gymplyapp',
    authDomain: 'gymplyapp.firebaseapp.com',
    storageBucket: 'gymplyapp.firebasestorage.app',
    measurementId: 'G-MBH2SK8PGY',
  );

}