// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gymply/models/cardio_model.dart';
import 'package:gymply/models/settings_model.dart';
import 'package:gymply/models/strength_model.dart';
import 'package:gymply/models/stretch_model.dart';
import 'package:gymply/models/workout_model.dart';
import 'package:gymply/services/filter_service.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CardioExerciseAdapter());
    registerAdapter(CardioSetAdapter());
    registerAdapter(EquipmentAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(StrengthExerciseAdapter());
    registerAdapter(StrengthSetAdapter());
    registerAdapter(StretchExerciseAdapter());
    registerAdapter(StretchSetAdapter());
    registerAdapter(WorkoutAdapter());
    registerAdapter(WorkoutTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CardioExerciseAdapter());
    registerAdapter(CardioSetAdapter());
    registerAdapter(EquipmentAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(StrengthExerciseAdapter());
    registerAdapter(StrengthSetAdapter());
    registerAdapter(StretchExerciseAdapter());
    registerAdapter(StretchSetAdapter());
    registerAdapter(WorkoutAdapter());
    registerAdapter(WorkoutTypeAdapter());
  }
}
